### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Madji** [antirek/lcr-finder#5]
node -v
v8.9.4
Distributor ID: Debian
Description:    Debian GNU/Linux 8.10 (jessie)
Release:        8.10
Codename:       jessie

db version v3.4.13
git version: fbdef2ccc53e0fcc9afb570063633d992b2aae42
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: debian81
    distarch: x86_64
    target_arch: x86_64

2018-2-16 14:44:13 - info: server started undefined
(node:3405) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Object.start (/var/service/asterisk/lcr-finder-app/node_modules/ding-dong/lib/index.js:20:48)
    at init (/var/service/asterisk/lcr-finder-app/node_modules/lcr-finder/index.js:46:19)
    at /var/service/asterisk/lcr-finder-app/node_modules/lcr-finder/index.js:60:17
    at internals.Object.internals.Any._validateWithOptions (/var/service/asterisk/lcr-finder-app/node_modules/joi/lib/any.js:657:16)
    at module.exports.internals.Any.root.validate (/var/service/asterisk/lcr-finder-app/node_modules/joi/lib/index.js:100:23)
    at validate (/var/service/asterisk/lcr-finder-app/node_modules/lcr-finder/index.js:27:13)
    at Server.start (/var/service/asterisk/lcr-finder-app/node_modules/lcr-finder/index.js:55:9)
    at Object.<anonymous> (/var/service/asterisk/lcr-finder-app/app.js:6:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

**Comment by Madji** [comment]
Больше не работает. а очень хотелось бы. спасибо

**Comment by antirek** [comment]
Error: listen EADDRINUSE :::3000 ?   наверное, порт занят?

**Comment by Madji** [comment]
Ок освободил порт. спасибо вы были правы.
(node:30240) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
(node:30240) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
